[2025-04-01T08:47:03.663+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load scheduled__2025-04-01T07:40:00+00:00 [queued]>
[2025-04-01T08:47:03.669+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load scheduled__2025-04-01T07:40:00+00:00 [queued]>
[2025-04-01T08:47:03.670+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-01T08:47:03.679+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2025-04-01 07:40:00+00:00
[2025-04-01T08:47:03.684+0000] {standard_task_runner.py:57} INFO - Started process 261 to run task
[2025-04-01T08:47:03.685+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'load', 'scheduled__2025-04-01T07:40:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpfn_k4rwd']
[2025-04-01T08:47:03.687+0000] {standard_task_runner.py:85} INFO - Job 197: Subtask load
[2025-04-01T08:47:03.698+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-01T08:47:03.722+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.load scheduled__2025-04-01T07:40:00+00:00 [running]> on host 07e8187327cf
[2025-04-01T08:47:03.769+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T07:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T07:40:00+00:00'
[2025-04-01T08:47:07.122+0000] {logging_mixin.py:154} INFO - 4 nguồn dữ liệu đã load xong, bắt đầu load AQI...
[2025-04-01T08:47:08.199+0000] {logging_mixin.py:154} INFO - Load hoàn tất ❤️
[2025-04-01T08:47:08.265+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-01T08:47:08.271+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load, execution_date=20250401T074000, start_date=20250401T084703, end_date=20250401T084708
[2025-04-01T08:47:08.290+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-01T08:47:08.300+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
