[2025-04-01T12:52:13.321+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load scheduled__2025-04-01T11:45:00+00:00 [queued]>
[2025-04-01T12:52:13.329+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load scheduled__2025-04-01T11:45:00+00:00 [queued]>
[2025-04-01T12:52:13.330+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-01T12:52:13.338+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2025-04-01 11:45:00+00:00
[2025-04-01T12:52:13.342+0000] {standard_task_runner.py:57} INFO - Started process 432 to run task
[2025-04-01T12:52:13.344+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'load', 'scheduled__2025-04-01T11:45:00+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpgeyo00__']
[2025-04-01T12:52:13.387+0000] {standard_task_runner.py:85} INFO - Job 221: Subtask load
[2025-04-01T12:52:13.399+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-01T12:52:13.431+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.load scheduled__2025-04-01T11:45:00+00:00 [running]> on host f263ca9a5772
[2025-04-01T12:52:13.500+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T11:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T11:45:00+00:00'
[2025-04-01T12:52:22.675+0000] {logging_mixin.py:154} INFO - 4 nguồn dữ liệu đã load xong, bắt đầu load AQI...
[2025-04-01T12:52:24.505+0000] {logging_mixin.py:154} INFO - Load hoàn tất ❤️
[2025-04-01T12:52:24.582+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-01T12:52:24.589+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load, execution_date=20250401T114500, start_date=20250401T125213, end_date=20250401T125224
[2025-04-01T12:52:24.639+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-01T12:52:24.649+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
