[2025-04-01T11:52:29.633+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load scheduled__2025-04-01T10:45:00+00:00 [queued]>
[2025-04-01T11:52:29.639+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load scheduled__2025-04-01T10:45:00+00:00 [queued]>
[2025-04-01T11:52:29.639+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-01T11:52:29.649+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2025-04-01 10:45:00+00:00
[2025-04-01T11:52:29.653+0000] {standard_task_runner.py:57} INFO - Started process 141 to run task
[2025-04-01T11:52:29.655+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'load', 'scheduled__2025-04-01T10:45:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmp4jm5_4ko']
[2025-04-01T11:52:29.657+0000] {standard_task_runner.py:85} INFO - Job 218: Subtask load
[2025-04-01T11:52:29.668+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-01T11:52:29.692+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.load scheduled__2025-04-01T10:45:00+00:00 [running]> on host f263ca9a5772
[2025-04-01T11:52:29.748+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T10:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T10:45:00+00:00'
[2025-04-01T11:52:33.693+0000] {logging_mixin.py:154} INFO - 4 nguồn dữ liệu đã load xong, bắt đầu load AQI...
[2025-04-01T11:52:34.982+0000] {logging_mixin.py:154} INFO - Load hoàn tất ❤️
[2025-04-01T11:52:35.054+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-01T11:52:35.061+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load, execution_date=20250401T104500, start_date=20250401T115229, end_date=20250401T115235
[2025-04-01T11:52:35.082+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-01T11:52:35.093+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
