[2025-03-19T07:38:47.842+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:38:47.848+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:38:47.848+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-19T07:38:47.857+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2025-03-19 06:10:00+00:00
[2025-03-19T07:38:47.861+0000] {standard_task_runner.py:57} INFO - Started process 157 to run task
[2025-03-19T07:38:47.863+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'transform', 'scheduled__2025-03-19T06:10:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpop9nd466']
[2025-03-19T07:38:47.864+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask transform
[2025-03-19T07:38:47.874+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-19T07:38:47.897+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.transform scheduled__2025-03-19T06:10:00+00:00 [running]> on host 9431682cb7a1
[2025-03-19T07:38:47.946+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T06:10:00+00:00'
[2025-03-19T07:38:47.996+0000] {logging_mixin.py:154} INFO - Index(['location_id', 'aqi_us', 'main_us', 'aqi_cn', 'main_cn', 'timestamp',
       'aqi_us_category', 'aqi_cn_category', 'aqi_avg', 'main_pollutant',
       'severe_pollution', 'traffic_id', 'weather_id', 'fact_id'],
      dtype='object')
[2025-03-19T07:38:48.006+0000] {logging_mixin.py:154} INFO - ✅ Dữ liệu đã được xử lý và lưu vào processed_data
[2025-03-19T07:38:48.006+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-19T07:38:48.013+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=transform, execution_date=20250319T061000, start_date=20250319T073847, end_date=20250319T073848
[2025-03-19T07:38:48.037+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-19T07:38:48.051+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-19T07:50:54.147+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:50:54.152+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:50:54.153+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-19T07:50:54.162+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2025-03-19 06:10:00+00:00
[2025-03-19T07:50:54.165+0000] {standard_task_runner.py:57} INFO - Started process 178 to run task
[2025-03-19T07:50:54.167+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'transform', 'scheduled__2025-03-19T06:10:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmp42_n3ixc']
[2025-03-19T07:50:54.168+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask transform
[2025-03-19T07:50:54.179+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-19T07:50:54.203+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.transform scheduled__2025-03-19T06:10:00+00:00 [running]> on host 9431682cb7a1
[2025-03-19T07:50:54.251+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T06:10:00+00:00'
[2025-03-19T07:50:54.274+0000] {logging_mixin.py:154} INFO - Index(['location_id', 'aqi_us', 'main_us', 'aqi_cn', 'main_cn', 'timestamp',
       'aqi_us_category', 'aqi_cn_category', 'aqi_avg', 'main_pollutant',
       'severe_pollution', 'traffic_id', 'weather_id', 'fact_id'],
      dtype='object')
[2025-03-19T07:50:54.280+0000] {logging_mixin.py:154} INFO - ✅ Dữ liệu đã được xử lý và lưu vào processed_data
[2025-03-19T07:50:54.280+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-19T07:50:54.286+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=transform, execution_date=20250319T061000, start_date=20250319T075054, end_date=20250319T075054
[2025-03-19T07:50:54.300+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-19T07:50:54.313+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
